[package]
name = "emilgardis-test-crate"
version = "0.0.1"
edition = "2021"
license = "WTFPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
