on:
  pull_request:
  push:
    branches: [main, staging, trying]
    tags:
      - "v*.*.*"

name: CI

env:
  CARGO_NET_RETRY: 3
  CARGO_HTTP_CHECK_REVOKE: false

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-rust
        with:
          components: rustfmt

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { target: x86_64-apple-darwin,              os: macos-10.15 }
          - { target: x86_64-unknown-linux-gnu,         os: ubuntu-latest }
          - { target: x86_64-unknown-linux-musl,        os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc,           os: windows-2019 }
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
      - uses: ./.github/actions/cargo-install-upload-artifacts
        with:
          target: ${{ matrix.target }}

  publish:
    permissions:
      contents: write
    needs: [test, binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
      - uses: ./.github/actions/cargo-publish
        with:
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
